// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/board.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/profile.tsx";
import * as $5 from "./routes/signin.tsx";
import * as $6 from "./routes/signup.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Menu.tsx";
import * as $$2 from "./islands/Signin.tsx";
import * as $$3 from "./islands/Signup.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/board.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/profile.tsx": $4,
    "./routes/signin.tsx": $5,
    "./routes/signup.tsx": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Menu.tsx": $$1,
    "./islands/Signin.tsx": $$2,
    "./islands/Signup.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
