/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppBoard {
    }
    interface AppHome {
    }
    interface AppMenu {
    }
    interface AppProfile {
    }
    interface AppRoot {
    }
    interface AppSignIn {
    }
    interface AppSignUp {
    }
}
declare global {
    interface HTMLAppBoardElement extends Components.AppBoard, HTMLStencilElement {
    }
    var HTMLAppBoardElement: {
        prototype: HTMLAppBoardElement;
        new (): HTMLAppBoardElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {
    }
    var HTMLAppMenuElement: {
        prototype: HTMLAppMenuElement;
        new (): HTMLAppMenuElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSignInElement extends Components.AppSignIn, HTMLStencilElement {
    }
    var HTMLAppSignInElement: {
        prototype: HTMLAppSignInElement;
        new (): HTMLAppSignInElement;
    };
    interface HTMLAppSignUpElement extends Components.AppSignUp, HTMLStencilElement {
    }
    var HTMLAppSignUpElement: {
        prototype: HTMLAppSignUpElement;
        new (): HTMLAppSignUpElement;
    };
    interface HTMLElementTagNameMap {
        "app-board": HTMLAppBoardElement;
        "app-home": HTMLAppHomeElement;
        "app-menu": HTMLAppMenuElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-sign-in": HTMLAppSignInElement;
        "app-sign-up": HTMLAppSignUpElement;
    }
}
declare namespace LocalJSX {
    interface AppBoard {
    }
    interface AppHome {
    }
    interface AppMenu {
    }
    interface AppProfile {
    }
    interface AppRoot {
    }
    interface AppSignIn {
    }
    interface AppSignUp {
    }
    interface IntrinsicElements {
        "app-board": AppBoard;
        "app-home": AppHome;
        "app-menu": AppMenu;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-sign-in": AppSignIn;
        "app-sign-up": AppSignUp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-board": LocalJSX.AppBoard & JSXBase.HTMLAttributes<HTMLAppBoardElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-menu": LocalJSX.AppMenu & JSXBase.HTMLAttributes<HTMLAppMenuElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-sign-in": LocalJSX.AppSignIn & JSXBase.HTMLAttributes<HTMLAppSignInElement>;
            "app-sign-up": LocalJSX.AppSignUp & JSXBase.HTMLAttributes<HTMLAppSignUpElement>;
        }
    }
}
